// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`betterer should throws when reading the results file fails 1`] = `
Array [
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|


Error: could not read results from \\"<project>/fixtures/test-betterer-failed-reading/.betterer.results\\". ğŸ˜”
      at Object.parse (<project>/packages/betterer/dist/results/parser.js:1067:11)
      at BettererResults.getExpectedNames (<project>/packages/betterer/dist/results/results.js:816:32)
      at BettererContextÎ©._initObsolete (<project>/packages/betterer/dist/context/context.js:2220:31)
      at BettererContextÎ©.run (<project>/packages/betterer/dist/context/context.js:1968:31)
      at <project>/packages/betterer/dist/betterer.js:909:32
      at runContext (<project>/packages/betterer/dist/betterer.js:1074:12)
      at <project>/test/betterer-failed.spec.ts:49:34
      at Object.<anonymous> (<project>/test/betterer-failed.spec.ts:49:9)
",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|


Error: could not read results from \\"<project>/fixtures/test-betterer-failed-reading/.betterer.results\\". ğŸ˜”
      at Object.parse (<project>/packages/betterer/dist/results/parser.js:1067:11)
      at BettererResults.getExpectedNames (<project>/packages/betterer/dist/results/results.js:816:32)
      at BettererContextÎ©._initObsolete (<project>/packages/betterer/dist/context/context.js:2220:31)
      at BettererContextÎ©.run (<project>/packages/betterer/dist/context/context.js:1968:31)
      at <project>/packages/betterer/dist/betterer.js:909:32
      at runContext (<project>/packages/betterer/dist/betterer.js:1074:12)
      at <project>/test/betterer-failed.spec.ts:49:34
      at Object.<anonymous> (<project>/test/betterer-failed.spec.ts:49:9)
",
]
`;

exports[`betterer should work when a test fails 1`] = `
Array [
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

ğŸŒŸ Betterer (0ms):
",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

ğŸŒŸ Betterer (0ms): 1 test running...
ğŸ¤” throws error: running \\"throws error\\"!
",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

ğŸŒŸ Betterer (0ms): 1 test running...
ğŸ”¥ throws error: OH NO!
",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

ğŸŒŸ Betterer (0ms): 1 test running...

Error: OH NO!
      at Object.test (<project>/fixtures/test-betterer-failed/.betterer.js:6:13)
      at runTest (<project>/packages/betterer/dist/runner/runner.js:977:55)
      at <project>/packages/betterer/dist/runner/runner.js:926:7
      at <project>/packages/betterer/dist/runner/runner.js:915:5
      at BettererContextÎ©.run (<project>/packages/betterer/dist/context/context.js:2023:5)
      at <project>/packages/betterer/dist/betterer.js:909:32
      at runContext (<project>/packages/betterer/dist/betterer.js:1074:12)
      at Object.<anonymous> (<project>/test/betterer-failed.spec.ts:23:26)
ğŸ”¥ throws error: OH NO!
",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

ğŸ’¥ Betterer (0ms): 1 test done! 1 test errored!

Error: OH NO!
      at Object.test (<project>/fixtures/test-betterer-failed/.betterer.js:6:13)
      at runTest (<project>/packages/betterer/dist/runner/runner.js:977:55)
      at <project>/packages/betterer/dist/runner/runner.js:926:7
      at <project>/packages/betterer/dist/runner/runner.js:915:5
      at BettererContextÎ©.run (<project>/packages/betterer/dist/context/context.js:2023:5)
      at <project>/packages/betterer/dist/betterer.js:909:32
      at runContext (<project>/packages/betterer/dist/betterer.js:1074:12)
      at Object.<anonymous> (<project>/test/betterer-failed.spec.ts:23:26)
ğŸ”¥ throws error: OH NO!
",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

ğŸ’¥ Betterer (0ms): 1 test done! 1 test errored!
ğŸ”¥ throws error: OH NO!

Error: OH NO!
      at Object.test (<project>/fixtures/test-betterer-failed/.betterer.js:6:13)
      at runTest (<project>/packages/betterer/dist/runner/runner.js:977:55)
      at <project>/packages/betterer/dist/runner/runner.js:926:7
      at <project>/packages/betterer/dist/runner/runner.js:915:5
      at BettererContextÎ©.run (<project>/packages/betterer/dist/context/context.js:2023:5)
      at <project>/packages/betterer/dist/betterer.js:909:32
      at runContext (<project>/packages/betterer/dist/betterer.js:1074:12)
      at Object.<anonymous> (<project>/test/betterer-failed.spec.ts:23:26)
",
  "
   / | /     _         _   _
 '-.ooo.-'  | |__  ___| |_| |_ ___ _ __ ___ _ __
---ooooo--- | '_ // _ / __| __/ _ / '__/ _ / '__|
 .-'ooo'-.  | |_)|  __/ |_| ||  __/ | |  __/ |
   / | /    |_.__//___|/__|/__/___|_|  /___|_|

ğŸ’¥ Betterer (0ms): 1 test done! 1 test errored!
ğŸ”¥ throws error: OH NO!

Error: OH NO!
      at Object.test (<project>/fixtures/test-betterer-failed/.betterer.js:6:13)
      at runTest (<project>/packages/betterer/dist/runner/runner.js:977:55)
      at <project>/packages/betterer/dist/runner/runner.js:926:7
      at <project>/packages/betterer/dist/runner/runner.js:915:5
      at BettererContextÎ©.run (<project>/packages/betterer/dist/context/context.js:2023:5)
      at <project>/packages/betterer/dist/betterer.js:909:32
      at runContext (<project>/packages/betterer/dist/betterer.js:1074:12)
      at Object.<anonymous> (<project>/test/betterer-failed.spec.ts:23:26)

0 tests got checked. ğŸ¤”
1 test failed to run. ğŸ”¥

",
]
`;

exports[`betterer should work when a test fails 2`] = `"// BETTERER RESULTS V2."`;
